/** Shared inline styles for management screens (NHS-aligned blues). */

export const managementStyles = {
  page: { padding: "1.5rem", maxWidth: 960, margin: "0 auto" } as const,
  h1: { marginTop: 0, color: "#0f172a" } as const,
  muted: { color: "#64748b", fontSize: 14 } as const,
  btnPrimary: {
    padding: "10px 18px",
    background: "#005eb8",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    fontWeight: 700,
    cursor: "pointer",
    fontSize: 14,
  } as const,
  btnGhost: {
    padding: "10px 18px",
    background: "#f1f5f9",
    color: "#334155",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    fontWeight: 600,
    cursor: "pointer",
    fontSize: 14,
  } as const,
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: 14,
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 8,
    overflow: "hidden",
  } as const,
  th: { padding: "10px 12px", borderBottom: "1px solid #e2e8f0", background: "#f8fafc", textAlign: "left" as const },
  td: { padding: "10px 12px", borderBottom: "1px solid #f1f5f9" } as const,
  select: { padding: "8px 10px", borderRadius: 8, border: "1px solid #cbd5e1", minWidth: 160, fontSize: 13 } as const,
  label: { display: "flex", flexDirection: "column" as const, gap: 6, fontWeight: 700, fontSize: 13, marginBottom: 12, color: "#0f172a" } as const,
  input: { padding: "10px 12px", borderRadius: 8, border: "1px solid #cbd5e1", fontSize: 14 } as const,
  modalBackdrop: {
    position: "fixed" as const,
    inset: 0,
    background: "rgba(15,23,42,0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 80,
  },
  modalCard: {
    background: "#fff",
    borderRadius: 12,
    padding: "1.25rem 1.5rem",
    maxWidth: 440,
    width: "100%",
    boxShadow: "0 12px 40px rgba(0,0,0,0.2)",
  },
  alert: { color: "#b91c1c", fontSize: 14 } as const,
  callout: {
    padding: "12px 14px",
    background: "#fffbeb",
    border: "1px solid #fde68a",
    borderRadius: 10,
    color: "#92400e",
    fontSize: 14,
  } as const,
};
